// Generated by CoffeeScript 1.3.3
(function() {

  window.App || (window.App = {});

  App.LocalStorage = (function() {

    function LocalStorage() {}

    LocalStorage.nextIdFor = function(name) {
      return this.all(name).length + 1;
    };

    LocalStorage.all = function(name) {
      if (!localStorage.getItem(name)) {
        localStorage.setItem(name, JSON.stringify([]));
      }
      return JSON.parse(localStorage.getItem(name));
    };

    LocalStorage.get = function(name, id) {
      return _.findWhere(this.all(name), {
        id: id
      });
    };

    LocalStorage.set = function(name, obj) {
      var all, ids;
      obj.id || (obj.id = this.nextIdFor(name));
      obj.id = parseInt(obj.id);
      all = this.all(name);
      ids = _.pluck(all, 'id');
      if (ids.indexOf(obj.id) > -1) {
        all.splice(ids.indexOf(obj.id), 1);
      }
      all.push(obj);
      return localStorage.setItem(name, JSON.stringify(all));
    };

    return LocalStorage;

  })();

}).call(this);
